name: Post to Microsoft Teams

on: 
  push:
    branches:
      - main

jobs:
  post-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: oops
      run: exit 1
    - name: Send message to MS Teams
      if: always()
      env:
        MS_HOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        SERVICE_NAME: ${{ inputs.service_name }}
        SERVICE_VERSION: ${{ inputs.docker_tag}}
        ENVIRONMENT: ${{ inputs.environment }}
        JOB_STATUS: ${{ job.status }}
      run: |
        echo $JOB_STATUS
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
        COMMIT_URL="${{ github.event.head_commit.url }}"
        REPO_URL="https://github.com/${{ github.repository }}"
        RUN_ID="${{ github.run_id }}"
        WORKFLOW_URL="$REPO_URL/actions/runs/$RUN_ID"
        THEME_COLOR="0076D7" # Default to blue

        if [[ "$JOB_STATUS" != "success" ]]; then
          THEME_COLOR="FF0000" # Set to red if any job failed
        fi
        MESSAGE_PAYLOAD=$(cat <<EOF

        {
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "summary": "$ENVIRONMENT Deployment",
          "themeColor": "0076D7",
          "title": "$SERVICE_NAME $SERVICE_VERSION has been deployed to $ENVIRONMENT",
          "sections": [
            {
              "activityTitle": "Last commit by $COMMIT_AUTHOR",
              "activitySubtitle": "$COMMIT_MESSAGE",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [
                {
                  "name": "Repository:",
                  "value": "$REPO_URL"
                },
                {
                  "name": "Commit:",
                  "value": "[View Commit]($COMMIT_URL)"
                }
              ]
            }
          ],
          "potentialAction": [
            {
              "@type": "OpenUri",
              "name": "View Workflow",
              "targets": [
                { "os": "default", "uri": "$WORKFLOW_URL" }
              ]
            }
          ]
        }
        EOF
        )
        curl -H "Content-Type: application/json" \
             -d "$MESSAGE_PAYLOAD" \
             $MS_HOOK_URL