on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env: 
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: run
        run: |
          gh release create ${{ github.ref_name }} --generate-notes --prerelease --verify-tag 

