on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    # only run for tags on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: run
        run: echo "Creating release for tag ${{ github.ref_name }}"

