on:
  push:
    branches:
      - main

jobs:
  test:
    name: test workflow
    runs-on: ubuntu-latest
    steps:
      - id: set-variables
        name: Set Output Variable
        run: |
          MY_VAR="my-var"
          echo "var: $MY_VAR"
          echo "MY_VAR=$MY_VAR" >> $GITHUB_ENV
      - name: Use Output
        run: |
          echo "MY_VAR: $MY_VAR"
